# Generated by Django 3.2.12 on 2022-04-28 09:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifytoken',
            name='token',
            field=models.CharField(default=uuid.UUID('aff23a1d-536a-45b2-b256-273ea6bbf611'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
