# Generated by Django 3.2.12 on 2022-05-03 07:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifytoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='emailverifytoken',
            name='token',
            field=models.CharField(default=uuid.UUID('334abd16-70da-449b-ade6-e49372170b2d'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
