# Generated by Django 3.2.12 on 2022-05-03 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20220503_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailverifytoken',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='emailverifytoken',
            name='token',
            field=models.CharField(default=uuid.UUID('7ad553b2-ad31-4282-b391-44ec002c3445'), max_length=100, primary_key=True, serialize=False),
        ),
    ]
